import type { PetType, PetActionType } from '../types'

export const PET_TYPES: PetType[] = [
  {
    id: 'hamster',
    name: '小仓鼠',
    emoji: ['🐹', '🐹', '🐿️'],
    price: 40,
    description: '圆滚滚的小可爱，超级爱吃！',
    speciality: '喂食效果×1.6，入门首选',
    feedBonus: 1.6,
    cleanBonus: 1.0,
    playBonus: 1.0,
    hungerDecayRate: 1.0,
    dirtDecayRate: 1.0,
    happinessDecayRate: 1.0,
  },
  {
    id: 'cat',
    name: '小猫咪',
    emoji: ['🐱', '🐈', '🦁'],
    price: 50,
    description: '优雅的小猫，最爱干净整洁。',
    speciality: '洗澡效果×1.5，不太爱玩',
    feedBonus: 1.0,
    cleanBonus: 1.5,
    playBonus: 0.7,
    hungerDecayRate: 1.0,
    dirtDecayRate: 1.2,
    happinessDecayRate: 0.8,
  },
  {
    id: 'dog',
    name: '小狗狗',
    emoji: ['🐶', '🐕', '🦮'],
    price: 50,
    description: '活泼的小狗，最喜欢和你玩耍！',
    speciality: '玩耍效果×1.5，最好养',
    feedBonus: 1.0,
    cleanBonus: 1.0,
    playBonus: 1.5,
    hungerDecayRate: 0.9,
    dirtDecayRate: 0.9,
    happinessDecayRate: 0.9,
  },
  {
    id: 'rabbit',
    name: '小兔子',
    emoji: ['🐰', '🐇', '🐇'],
    price: 60,
    description: '萌萌的兔兔，需要经常陪伴。',
    speciality: '快乐度衰减快×1.5，需常陪',
    feedBonus: 1.0,
    cleanBonus: 1.0,
    playBonus: 1.2,
    hungerDecayRate: 1.0,
    dirtDecayRate: 1.0,
    happinessDecayRate: 1.5,
  },
  {
    id: 'penguin',
    name: '小企鹅',
    emoji: ['🐧', '🐧', '🐧'],
    price: 80,
    description: '可爱的企鹅，各方面都很均衡！',
    speciality: '各属性均衡，清洁度衰减慢',
    feedBonus: 1.1,
    cleanBonus: 1.1,
    playBonus: 1.1,
    hungerDecayRate: 0.9,
    dirtDecayRate: 0.6,
    happinessDecayRate: 0.9,
  },
  {
    id: 'dragon',
    name: '小龙龙',
    emoji: ['🐣', '🦎', '🐉'],
    price: 150,
    description: '神秘的小龙，传说中的珍稀宠物！',
    speciality: '全属性×1.2，衰减最慢',
    feedBonus: 1.2,
    cleanBonus: 1.2,
    playBonus: 1.2,
    hungerDecayRate: 0.6,
    dirtDecayRate: 0.6,
    happinessDecayRate: 0.6,
  },
]

export const PET_ACTIONS: Record<PetActionType, { label: string; emoji: string; cost: number; baseEffect: number; stat: 'hunger' | 'cleanliness' | 'happiness' }> = {
  feed: { label: '喂食', emoji: '🍖', cost: 5, baseEffect: 25, stat: 'hunger' },
  clean: { label: '洗澡', emoji: '🛁', cost: 5, baseEffect: 30, stat: 'cleanliness' },
  play: { label: '玩耍', emoji: '🎾', cost: 8, baseEffect: 35, stat: 'happiness' },
}

export const STAGE_THRESHOLDS = {
  baby: 0,
  teen: 20,
  adult: 50,
}
